services:
  reaper:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=docker
      - HOST=0.0.0.0
      - PORT=8000
      - PROXY_PORT=8080
      - URL=https://api.deepseek.com/v1/
      - OPENAI_API_KEY=sk-1XXXxxXXXXX
      - MODEL=deepseek-chat
    volumes:
      - ./files:/app/files
    ports:
      - 8000:8000
      - 8080:8080
